//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabProg.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConfocalLevel {
            get {
                return ((string)(this["ConfocalLevel"]));
            }
            set {
                this["ConfocalLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PumpReverse {
            get {
                return ((bool)(this["PumpReverse"]));
            }
            set {
                this["PumpReverse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PumpActive {
            get {
                return ((bool)(this["PumpActive"]));
            }
            set {
                this["PumpActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PumpManaging {
            get {
                return ((bool)(this["PumpManaging"]));
            }
            set {
                this["PumpManaging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PumpSettings {
            get {
                return ((bool)(this["PumpSettings"]));
            }
            set {
                this["PumpSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MirrorSetup {
            get {
                return ((bool)(this["MirrorSetup"]));
            }
            set {
                this["MirrorSetup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MirrorManaging {
            get {
                return ((bool)(this["MirrorManaging"]));
            }
            set {
                this["MirrorManaging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("301,844")]
        public string MirrorLeftPoint {
            get {
                return ((string)(this["MirrorLeftPoint"]));
            }
            set {
                this["MirrorLeftPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("304,578")]
        public string MirrorRightPoint {
            get {
                return ((string)(this["MirrorRightPoint"]));
            }
            set {
                this["MirrorRightPoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,02")]
        public string MirrorJogStep {
            get {
                return ((string)(this["MirrorJogStep"]));
            }
            set {
                this["MirrorJogStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrModeCh1 {
            get {
                return ((int)(this["PwrModeCh1"]));
            }
            set {
                this["PwrModeCh1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExChannel1 {
            get {
                return ((bool)(this["ExChannel1"]));
            }
            set {
                this["ExChannel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CbChannel1On {
            get {
                return ((bool)(this["CbChannel1On"]));
            }
            set {
                this["CbChannel1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrPortIndex {
            get {
                return ((int)(this["PwrPortIndex"]));
            }
            set {
                this["PwrPortIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PowerManaging {
            get {
                return ((bool)(this["PowerManaging"]));
            }
            set {
                this["PowerManaging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CbChannel2On {
            get {
                return ((bool)(this["CbChannel2On"]));
            }
            set {
                this["CbChannel2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh0MaxVolts {
            get {
                return ((string)(this["PwrCh0MaxVolts"]));
            }
            set {
                this["PwrCh0MaxVolts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CbChannel3On {
            get {
                return ((bool)(this["CbChannel3On"]));
            }
            set {
                this["CbChannel3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CbChannel4On {
            get {
                return ((bool)(this["CbChannel4On"]));
            }
            set {
                this["CbChannel4On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CbChannel5On {
            get {
                return ((bool)(this["CbChannel5On"]));
            }
            set {
                this["CbChannel5On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh0Bias {
            get {
                return ((string)(this["PwrCh0Bias"]));
            }
            set {
                this["PwrCh0Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh1Bias {
            get {
                return ((string)(this["PwrCh1Bias"]));
            }
            set {
                this["PwrCh1Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh2Bias {
            get {
                return ((string)(this["PwrCh2Bias"]));
            }
            set {
                this["PwrCh2Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh3Bias {
            get {
                return ((string)(this["PwrCh3Bias"]));
            }
            set {
                this["PwrCh3Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh4Bias {
            get {
                return ((string)(this["PwrCh4Bias"]));
            }
            set {
                this["PwrCh4Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh5Bias {
            get {
                return ((string)(this["PwrCh5Bias"]));
            }
            set {
                this["PwrCh5Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrModeCh2 {
            get {
                return ((int)(this["PwrModeCh2"]));
            }
            set {
                this["PwrModeCh2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrModeCh3 {
            get {
                return ((int)(this["PwrModeCh3"]));
            }
            set {
                this["PwrModeCh3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrModeCh4 {
            get {
                return ((int)(this["PwrModeCh4"]));
            }
            set {
                this["PwrModeCh4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrModeCh5 {
            get {
                return ((int)(this["PwrModeCh5"]));
            }
            set {
                this["PwrModeCh5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrModeCh0 {
            get {
                return ((int)(this["PwrModeCh0"]));
            }
            set {
                this["PwrModeCh0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh1MaxVolts {
            get {
                return ((string)(this["PwrCh1MaxVolts"]));
            }
            set {
                this["PwrCh1MaxVolts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh2MaxVolts {
            get {
                return ((string)(this["PwrCh2MaxVolts"]));
            }
            set {
                this["PwrCh2MaxVolts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh3MaxVolts {
            get {
                return ((string)(this["PwrCh3MaxVolts"]));
            }
            set {
                this["PwrCh3MaxVolts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh4MaxVolts {
            get {
                return ((string)(this["PwrCh4MaxVolts"]));
            }
            set {
                this["PwrCh4MaxVolts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PwrCh5MaxVolts {
            get {
                return ((string)(this["PwrCh5MaxVolts"]));
            }
            set {
                this["PwrCh5MaxVolts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CbChannel0On {
            get {
                return ((bool)(this["CbChannel0On"]));
            }
            set {
                this["CbChannel0On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LvlPortIndex {
            get {
                return ((int)(this["LvlPortIndex"]));
            }
            set {
                this["LvlPortIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExLaserManage {
            get {
                return ((bool)(this["ExLaserManage"]));
            }
            set {
                this["ExLaserManage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LaserPower {
            get {
                return ((string)(this["LaserPower"]));
            }
            set {
                this["LaserPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExLaserSettings {
            get {
                return ((bool)(this["ExLaserSettings"]));
            }
            set {
                this["ExLaserSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LaserPortIndex {
            get {
                return ((int)(this["LaserPortIndex"]));
            }
            set {
                this["LaserPortIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PyroTemp {
            get {
                return ((string)(this["PyroTemp"]));
            }
            set {
                this["PyroTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PyroPortIndex {
            get {
                return ((int)(this["PyroPortIndex"]));
            }
            set {
                this["PyroPortIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PowMax {
            get {
                return ((string)(this["PowMax"]));
            }
            set {
                this["PowMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempMax {
            get {
                return ((string)(this["TempMax"]));
            }
            set {
                this["TempMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PowMid {
            get {
                return ((string)(this["PowMid"]));
            }
            set {
                this["PowMid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempMid {
            get {
                return ((string)(this["TempMid"]));
            }
            set {
                this["TempMid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PowMin {
            get {
                return ((string)(this["PowMin"]));
            }
            set {
                this["PowMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TempMin {
            get {
                return ((string)(this["TempMin"]));
            }
            set {
                this["TempMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FreqCam {
            get {
                return ((string)(this["FreqCam"]));
            }
            set {
                this["FreqCam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CameraSavePath {
            get {
                return ((string)(this["CameraSavePath"]));
            }
            set {
                this["CameraSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CameraSavePrefix {
            get {
                return ((string)(this["CameraSavePrefix"]));
            }
            set {
                this["CameraSavePrefix"] = value;
            }
        }
    }
}
