//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabControl.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включение каналов:.
        /// </summary>
        internal static string LabelChanelsSwitch {
            get {
                return ResourceManager.GetString("LabelChanelsSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канал 0: (УФ диод 1).
        /// </summary>
        internal static string LabelChannel0 {
            get {
                return ResourceManager.GetString("LabelChannel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канал 1: (УФ диод 2).
        /// </summary>
        internal static string LabelChannel1 {
            get {
                return ResourceManager.GetString("LabelChannel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канал 2: (ИК источник 1).
        /// </summary>
        internal static string LabelChannel2 {
            get {
                return ResourceManager.GetString("LabelChannel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канал 3: (ИК источник 2).
        /// </summary>
        internal static string LabelChannel3 {
            get {
                return ResourceManager.GetString("LabelChannel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канал 4: (Микрокомпрессор).
        /// </summary>
        internal static string LabelChannel4 {
            get {
                return ResourceManager.GetString("LabelChannel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Канал 5: (Нагрев стекла).
        /// </summary>
        internal static string LabelChannel5 {
            get {
                return ResourceManager.GetString("LabelChannel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активность измерения.
        /// </summary>
        internal static string LabelConfocalActive {
            get {
                return ResourceManager.GetString("LabelConfocalActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показания датчика.
        /// </summary>
        internal static string LabelConfocalData {
            get {
                return ResourceManager.GetString("LabelConfocalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установленный уровень.
        /// </summary>
        internal static string LabelConfocalSetter {
            get {
                return ResourceManager.GetString("LabelConfocalSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая мощность.
        /// </summary>
        internal static string LabelCurrentPower {
            get {
                return ResourceManager.GetString("LabelCurrentPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Температура.
        /// </summary>
        internal static string LabelCurrentTemperature {
            get {
                return ResourceManager.GetString("LabelCurrentTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регулируемый ток (мА).
        /// </summary>
        internal static string LabelElectricFlow {
            get {
                return ResourceManager.GetString("LabelElectricFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Излучение!.
        /// </summary>
        internal static string LabelEmmitLaser {
            get {
                return ResourceManager.GetString("LabelEmmitLaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК Источник 1.
        /// </summary>
        internal static string LabelIkLed1 {
            get {
                return ResourceManager.GetString("LabelIkLed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИК Источник 2.
        /// </summary>
        internal static string LabelIkLed2 {
            get {
                return ResourceManager.GetString("LabelIkLed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт докачки.
        /// </summary>
        internal static string LabelInputPumpPort {
            get {
                return ResourceManager.GetString("LabelInputPumpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт лазера.
        /// </summary>
        internal static string LabelLaserPort {
            get {
                return ResourceManager.GetString("LabelLaserPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип лазера.
        /// </summary>
        internal static string LabelLaserType {
            get {
                return ResourceManager.GetString("LabelLaserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напряжение смещения (мВ).
        /// </summary>
        internal static string LabelOffsetVoltage {
            get {
                return ResourceManager.GetString("LabelOffsetVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить.
        /// </summary>
        internal static string LabelOn {
            get {
                return ResourceManager.GetString("LabelOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Один насос.
        /// </summary>
        internal static string LabelOnePump {
            get {
                return ResourceManager.GetString("LabelOnePump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт откачки.
        /// </summary>
        internal static string LabelOutputPumpPort {
            get {
                return ResourceManager.GetString("LabelOutputPumpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт пирометра.
        /// </summary>
        internal static string LabelPiroPort {
            get {
                return ResourceManager.GetString("LabelPiroPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соедениться с портом.
        /// </summary>
        internal static string LabelPortConnection {
            get {
                return ResourceManager.GetString("LabelPortConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Насос.
        /// </summary>
        internal static string LabelPump {
            get {
                return ResourceManager.GetString("LabelPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активность насоса(ов).
        /// </summary>
        internal static string LabelPumpActive {
            get {
                return ResourceManager.GetString("LabelPumpActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Насос докачки.
        /// </summary>
        internal static string LabelPumpIn {
            get {
                return ResourceManager.GetString("LabelPumpIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Насос откачки.
        /// </summary>
        internal static string LabelPumpOut {
            get {
                return ResourceManager.GetString("LabelPumpOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амплитуда колебаний.
        /// </summary>
        internal static string LabelPwrChannelAmplitude {
            get {
                return ResourceManager.GetString("LabelPwrChannelAmplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Напряжение смешения(Регулируемый ток).
        /// </summary>
        internal static string LabelPwrChannelBias {
            get {
                return ResourceManager.GetString("LabelPwrChannelBias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скважность(%).
        /// </summary>
        internal static string LabelPwrChannelDuty {
            get {
                return ResourceManager.GetString("LabelPwrChannelDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частота(Гц).
        /// </summary>
        internal static string LabelPwrChannelFreq {
            get {
                return ResourceManager.GetString("LabelPwrChannelFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Режим работы.
        /// </summary>
        internal static string LabelPwrChannelMode {
            get {
                return ResourceManager.GetString("LabelPwrChannelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фаза(градусы).
        /// </summary>
        internal static string LabelPwrChannelPhase {
            get {
                return ResourceManager.GetString("LabelPwrChannelPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальный ток.
        /// </summary>
        internal static string LabelPwrMaxAmps {
            get {
                return ResourceManager.GetString("LabelPwrMaxAmps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Максимальное напряжение.
        /// </summary>
        internal static string LabelPwrMaxVoltage {
            get {
                return ResourceManager.GetString("LabelPwrMaxVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт блока питания.
        /// </summary>
        internal static string LabelPwrPort {
            get {
                return ResourceManager.GetString("LabelPwrPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочитать.
        /// </summary>
        internal static string LabelRead {
            get {
                return ResourceManager.GetString("LabelRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить мощность.
        /// </summary>
        internal static string LabelSetterPower {
            get {
                return ResourceManager.GetString("LabelSetterPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры.
        /// </summary>
        internal static string LabelSettings {
            get {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Два насоса.
        /// </summary>
        internal static string LabelTwoPump {
            get {
                return ResourceManager.GetString("LabelTwoPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УФ Диод 1.
        /// </summary>
        internal static string LabelUfLed1 {
            get {
                return ResourceManager.GetString("LabelUfLed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УФ Диод 2.
        /// </summary>
        internal static string LabelUfLed2 {
            get {
                return ResourceManager.GetString("LabelUfLed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записать.
        /// </summary>
        internal static string LabelWrite {
            get {
                return ResourceManager.GetString("LabelWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление лазером.
        /// </summary>
        internal static string LaserOpeprationTitle {
            get {
                return ResourceManager.GetString("LaserOpeprationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        internal static string LogHeaderColumn1Name {
            get {
                return ResourceManager.GetString("LogHeaderColumn1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТЮМГУ, Лаборатория микрогидродинамики, X-Bio.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление блоком питания.
        /// </summary>
        internal static string PowerSuplyTitle {
            get {
                return ResourceManager.GetString("PowerSuplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление уровнем.
        /// </summary>
        internal static string PumpOperationTitle {
            get {
                return ResourceManager.GetString("PumpOperationTitle", resourceCulture);
            }
        }
    }
}
