//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabControl.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowHeight {
            get {
                return ((int)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowWidth {
            get {
                return ((int)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTwoPump {
            get {
                return ((bool)(this["IsTwoPump"]));
            }
            set {
                this["IsTwoPump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ConfocalLevelSetter {
            get {
                return ((double)(this["ConfocalLevelSetter"]));
            }
            set {
                this["ConfocalLevelSetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IncomingPumpPortSelected {
            get {
                return ((string)(this["IncomingPumpPortSelected"]));
            }
            set {
                this["IncomingPumpPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutloginPumpPortSelected {
            get {
                return ((string)(this["OutloginPumpPortSelected"]));
            }
            set {
                this["OutloginPumpPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LaserPowerSetter {
            get {
                return ((int)(this["LaserPowerSetter"]));
            }
            set {
                this["LaserPowerSetter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LaserPortSelected {
            get {
                return ((string)(this["LaserPortSelected"]));
            }
            set {
                this["LaserPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PyroPortSelected {
            get {
                return ((string)(this["PyroPortSelected"]));
            }
            set {
                this["PyroPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LaserTypeSelectedIndex {
            get {
                return ((int)(this["LaserTypeSelectedIndex"]));
            }
            set {
                this["LaserTypeSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh0Mode {
            get {
                return ((int)(this["PwrCh0Mode"]));
            }
            set {
                this["PwrCh0Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh0Bias {
            get {
                return ((int)(this["PwrCh0Bias"]));
            }
            set {
                this["PwrCh0Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh0Amplitude {
            get {
                return ((int)(this["PwrCh0Amplitude"]));
            }
            set {
                this["PwrCh0Amplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh0Freq {
            get {
                return ((int)(this["PwrCh0Freq"]));
            }
            set {
                this["PwrCh0Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh0Duty {
            get {
                return ((int)(this["PwrCh0Duty"]));
            }
            set {
                this["PwrCh0Duty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh0Phase {
            get {
                return ((int)(this["PwrCh0Phase"]));
            }
            set {
                this["PwrCh0Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh0MaxVoltage {
            get {
                return ((int)(this["PwrCh0MaxVoltage"]));
            }
            set {
                this["PwrCh0MaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh0MaxAmps {
            get {
                return ((int)(this["PwrCh0MaxAmps"]));
            }
            set {
                this["PwrCh0MaxAmps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh1Mode {
            get {
                return ((int)(this["PwrCh1Mode"]));
            }
            set {
                this["PwrCh1Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh1Bias {
            get {
                return ((int)(this["PwrCh1Bias"]));
            }
            set {
                this["PwrCh1Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh1Amplitude {
            get {
                return ((int)(this["PwrCh1Amplitude"]));
            }
            set {
                this["PwrCh1Amplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh1Freq {
            get {
                return ((int)(this["PwrCh1Freq"]));
            }
            set {
                this["PwrCh1Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh1Duty {
            get {
                return ((int)(this["PwrCh1Duty"]));
            }
            set {
                this["PwrCh1Duty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh1Phase {
            get {
                return ((int)(this["PwrCh1Phase"]));
            }
            set {
                this["PwrCh1Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh1MaxVoltage {
            get {
                return ((int)(this["PwrCh1MaxVoltage"]));
            }
            set {
                this["PwrCh1MaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh1MaxAmps {
            get {
                return ((int)(this["PwrCh1MaxAmps"]));
            }
            set {
                this["PwrCh1MaxAmps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh2Mode {
            get {
                return ((int)(this["PwrCh2Mode"]));
            }
            set {
                this["PwrCh2Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh2Bias {
            get {
                return ((int)(this["PwrCh2Bias"]));
            }
            set {
                this["PwrCh2Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh2Amplitude {
            get {
                return ((int)(this["PwrCh2Amplitude"]));
            }
            set {
                this["PwrCh2Amplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh2Freq {
            get {
                return ((int)(this["PwrCh2Freq"]));
            }
            set {
                this["PwrCh2Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh2Duty {
            get {
                return ((int)(this["PwrCh2Duty"]));
            }
            set {
                this["PwrCh2Duty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh2Phase {
            get {
                return ((int)(this["PwrCh2Phase"]));
            }
            set {
                this["PwrCh2Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh2MaxVoltage {
            get {
                return ((int)(this["PwrCh2MaxVoltage"]));
            }
            set {
                this["PwrCh2MaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh2MaxAmps {
            get {
                return ((int)(this["PwrCh2MaxAmps"]));
            }
            set {
                this["PwrCh2MaxAmps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PwrSwitchCh3 {
            get {
                return ((bool)(this["PwrSwitchCh3"]));
            }
            set {
                this["PwrSwitchCh3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh3Bias {
            get {
                return ((int)(this["PwrCh3Bias"]));
            }
            set {
                this["PwrCh3Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh3Amplitude {
            get {
                return ((int)(this["PwrCh3Amplitude"]));
            }
            set {
                this["PwrCh3Amplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh3Freq {
            get {
                return ((int)(this["PwrCh3Freq"]));
            }
            set {
                this["PwrCh3Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh3Duty {
            get {
                return ((int)(this["PwrCh3Duty"]));
            }
            set {
                this["PwrCh3Duty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh3Phase {
            get {
                return ((int)(this["PwrCh3Phase"]));
            }
            set {
                this["PwrCh3Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh3MaxVoltage {
            get {
                return ((int)(this["PwrCh3MaxVoltage"]));
            }
            set {
                this["PwrCh3MaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh3MaxAmps {
            get {
                return ((int)(this["PwrCh3MaxAmps"]));
            }
            set {
                this["PwrCh3MaxAmps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PwrSwitchCh4 {
            get {
                return ((bool)(this["PwrSwitchCh4"]));
            }
            set {
                this["PwrSwitchCh4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh3Mode {
            get {
                return ((int)(this["PwrCh3Mode"]));
            }
            set {
                this["PwrCh3Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh4Mode {
            get {
                return ((int)(this["PwrCh4Mode"]));
            }
            set {
                this["PwrCh4Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh4Bias {
            get {
                return ((int)(this["PwrCh4Bias"]));
            }
            set {
                this["PwrCh4Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh4Amplitude {
            get {
                return ((int)(this["PwrCh4Amplitude"]));
            }
            set {
                this["PwrCh4Amplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh4Freq {
            get {
                return ((int)(this["PwrCh4Freq"]));
            }
            set {
                this["PwrCh4Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh4Duty {
            get {
                return ((int)(this["PwrCh4Duty"]));
            }
            set {
                this["PwrCh4Duty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh4Phase {
            get {
                return ((int)(this["PwrCh4Phase"]));
            }
            set {
                this["PwrCh4Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh4MaxVoltage {
            get {
                return ((int)(this["PwrCh4MaxVoltage"]));
            }
            set {
                this["PwrCh4MaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh4MaxAmps {
            get {
                return ((int)(this["PwrCh4MaxAmps"]));
            }
            set {
                this["PwrCh4MaxAmps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrSwitchCh5 {
            get {
                return ((int)(this["PwrSwitchCh5"]));
            }
            set {
                this["PwrSwitchCh5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh5Mode {
            get {
                return ((int)(this["PwrCh5Mode"]));
            }
            set {
                this["PwrCh5Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh5Bias {
            get {
                return ((int)(this["PwrCh5Bias"]));
            }
            set {
                this["PwrCh5Bias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh5Amplitude {
            get {
                return ((int)(this["PwrCh5Amplitude"]));
            }
            set {
                this["PwrCh5Amplitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh5Freq {
            get {
                return ((int)(this["PwrCh5Freq"]));
            }
            set {
                this["PwrCh5Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh5Duty {
            get {
                return ((int)(this["PwrCh5Duty"]));
            }
            set {
                this["PwrCh5Duty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh5Phase {
            get {
                return ((int)(this["PwrCh5Phase"]));
            }
            set {
                this["PwrCh5Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh5MaxVoltage {
            get {
                return ((int)(this["PwrCh5MaxVoltage"]));
            }
            set {
                this["PwrCh5MaxVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PwrCh5MaxAmps {
            get {
                return ((int)(this["PwrCh5MaxAmps"]));
            }
            set {
                this["PwrCh5MaxAmps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string PwrPortSelected {
            get {
                return ((string)(this["PwrPortSelected"]));
            }
            set {
                this["PwrPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRevereFirstPump {
            get {
                return ((bool)(this["IsRevereFirstPump"]));
            }
            set {
                this["IsRevereFirstPump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsRevereSecondPump {
            get {
                return ((bool)(this["IsRevereSecondPump"]));
            }
            set {
                this["IsRevereSecondPump"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLaserEmit {
            get {
                return ((bool)(this["IsLaserEmit"]));
            }
            set {
                this["IsLaserEmit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPyroPortConnected {
            get {
                return ((bool)(this["IsPyroPortConnected"]));
            }
            set {
                this["IsPyroPortConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPyroActive {
            get {
                return ((bool)(this["IsPyroActive"]));
            }
            set {
                this["IsPyroActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DispenserPortSelected {
            get {
                return ((string)(this["DispenserPortSelected"]));
            }
            set {
                this["DispenserPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserSignalType {
            get {
                return ((int)(this["DispenserSignalType"]));
            }
            set {
                this["DispenserSignalType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserChannel {
            get {
                return ((int)(this["DispenserChannel"]));
            }
            set {
                this["DispenserChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserFrequency {
            get {
                return ((int)(this["DispenserFrequency"]));
            }
            set {
                this["DispenserFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserRiseTime {
            get {
                return ((int)(this["DispenserRiseTime"]));
            }
            set {
                this["DispenserRiseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserKeepTime {
            get {
                return ((int)(this["DispenserKeepTime"]));
            }
            set {
                this["DispenserKeepTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserFallTime {
            get {
                return ((int)(this["DispenserFallTime"]));
            }
            set {
                this["DispenserFallTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserLowTime {
            get {
                return ((int)(this["DispenserLowTime"]));
            }
            set {
                this["DispenserLowTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserRiseTime2 {
            get {
                return ((int)(this["DispenserRiseTime2"]));
            }
            set {
                this["DispenserRiseTime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserV0 {
            get {
                return ((int)(this["DispenserV0"]));
            }
            set {
                this["DispenserV0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserV1 {
            get {
                return ((int)(this["DispenserV1"]));
            }
            set {
                this["DispenserV1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserV2 {
            get {
                return ((int)(this["DispenserV2"]));
            }
            set {
                this["DispenserV2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserHV0 {
            get {
                return ((int)(this["DispenserHV0"]));
            }
            set {
                this["DispenserHV0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserHVpeak {
            get {
                return ((int)(this["DispenserHVpeak"]));
            }
            set {
                this["DispenserHVpeak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserHToverall {
            get {
                return ((int)(this["DispenserHToverall"]));
            }
            set {
                this["DispenserHToverall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AirSupportPressure {
            get {
                return ((int)(this["AirSupportPressure"]));
            }
            set {
                this["AirSupportPressure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PressureSensorPortSelected {
            get {
                return ((string)(this["PressureSensorPortSelected"]));
            }
            set {
                this["PressureSensorPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutgoingPumpPortSelected {
            get {
                return ((string)(this["OutgoingPumpPortSelected"]));
            }
            set {
                this["OutgoingPumpPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LightingUvChannelValue {
            get {
                return ((int)(this["LightingUvChannelValue"]));
            }
            set {
                this["LightingUvChannelValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LightingBlueChannelValue {
            get {
                return ((int)(this["LightingBlueChannelValue"]));
            }
            set {
                this["LightingBlueChannelValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LightingGreenRedChannelValue {
            get {
                return ((int)(this["LightingGreenRedChannelValue"]));
            }
            set {
                this["LightingGreenRedChannelValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSingleLighting {
            get {
                return ((bool)(this["IsSingleLighting"]));
            }
            set {
                this["IsSingleLighting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DispenserTypeSelectedIndex {
            get {
                return ((int)(this["DispenserTypeSelectedIndex"]));
            }
            set {
                this["DispenserTypeSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LightingPortSelected {
            get {
                return ((string)(this["LightingPortSelected"]));
            }
            set {
                this["LightingPortSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LightingPortSelectedIndex {
            get {
                return ((int)(this["LightingPortSelectedIndex"]));
            }
            set {
                this["LightingPortSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CoefficientA {
            get {
                return ((double)(this["CoefficientA"]));
            }
            set {
                this["CoefficientA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CoefficientB {
            get {
                return ((double)(this["CoefficientB"]));
            }
            set {
                this["CoefficientB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CoefficientC {
            get {
                return ((double)(this["CoefficientC"]));
            }
            set {
                this["CoefficientC"] = value;
            }
        }
    }
}
